name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  pr-validation:
    uses: HoneyDrunkStudios/HoneyDrunk.Actions/.github/workflows/templates/stages/pr-validation.yml@v1.0.0
    with:
      dotnet-version: '9.0.x'
      configuration: 'Release'
      runs-on: 'ubuntu-latest'
      working-directory: 'HoneyDrunk.Standards'
      enable-code-quality: true
      post-pr-comment: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
